apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goff-helm-redis
  namespace: argocd
spec:
  destination:
    namespace: pitc-goff
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - chart: redis
      helm:
        valueFiles:
          - $values/argocd/app/values.yaml
      repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 16.11.2
    - ref: values
      repoURL: 'https://github.com/puzzle/goff-gh-exmaple.git.git'
      targetRevision: main
